
POST http://localhost:3003/user/signup
Content-Type: application/json

{
   "email": "joao@hotmail.com" ,
   "password": "joao123",
   "role": "ADMIN" 
}

###

POST http://localhost:3003/user/login
Content-Type: application/json

{
   "email": "joao@hotmail.com" ,
   "password": "joao123"
}

###

GET http://localhost:3003/user/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImUzNmUyMmZhLWRjMTYtNDFlZC1iOWEzLTZiZjhmODdiOTI0YSIsImlhdCI6MTY1NjQ0NDYzNSwiZXhwIjoxNjU2NDQ1ODM1fQ.E0KWsonOvuYYqeYT5ZE7W1T8PnuEX-pywrUxoOepkXU
